### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by qmnl** [mailru/dbr#14]
Could you please create a new GitHub release or just version tag, because dependency managers like the official dep (https://github.com/golang/dep) use those versions by default.

**Comment by qmnl** [comment]
The last release is from 2016

**Comment by alvelcom** [comment]
Yes, the latest tag is `v2.1` that comes from gocraft and it creates a lot of confusion for `dep`.

**Comment by bgaifullin** [comment]
I have released new version [v3.0](https://github.com/mailru/dbr/releases/tag/v3.0)
Thanks for your report.

**Comment by qmnl** [comment]
Thanks!
