### ISSUE TITLE
can't use with go modules

### ISSUE THREAD

**Issue by im-kulikov** [mailru/dbr#16]
When I'll try to get latest stable version of `mailru/dbr`:

```
module some/project

require (
	...
	github.com/mailru/dbr v0.0.0-20180825184916-bee39f330c3b
	...
)
```

Problem is in release-tag naming:

`vX.Y` with `vX.Y.Z`

**Comment by bgaifullin** [comment]
there should be 3 components of version in tag name, is it?

**Comment by im-kulikov** [comment]
@bgaifullin yeah.. `X.Y.Z` and prefixed with `v` -> `v1.2.3`

**Comment by im-kulikov** [comment]
In order not to break anything, I suggest to add the following tags:
- v3.0.0 -> [v3.0](
https://github.com/mailru/dbr/releases/tag/v3.0)
- v2.1.0 -> [v2.1](
https://github.com/mailru/dbr/releases/tag/v2.1)
- v2.0.0 -> [v2.0](
https://github.com/mailru/dbr/releases/tag/v2.0)
- v1.1.0 -> [v1.1](
https://github.com/mailru/dbr/releases/tag/v1.1)

**Comment by bgaifullin** [comment]
add missing tags

**Comment by im-kulikov** [comment]
Thx!
