### ISSUE TITLE
Port 9000 is for clickhouse-client program

### ISSUE THREAD

**Issue by sir-farfan** [mailru/dbr#44]
Hello guys, I don't understand what I'm doing wrong, this IS a client program after all.
With sqlx I'm using "tcp://host:9000" and it works correctly, we're evaluating using dbr instead but it complains:
`unsupported protocol scheme "tcp"`

I've tried a bunch of things already, setting only host/default it complains until I call Load:
`panic: runtime error: index out of range [0] with length 0`
Actually, it doesn't matter what I put as host in Open(), I even tried with foo.var as host and it ran all the way to the call of query.Load()  xD

I tried with and without user, different ports, https scheme, I don't know what else to try, I haven't found any different examples here or otherwise.

Any suggestions?

```go
package main

import (
	"log"

	"github.com/mailru/dbr"
	_ "github.com/mailru/go-clickhouse"
)

func main() {
	connect, err := dbr.Open("clickhouse", "http://default@host:9000/default", nil)
	if err != nil {
		log.Fatalln(err)
	}
	sess := connect.NewSession(nil)
	query := sess.Select("start").From("sometable").Where(dbr.Eq("id", 3))

	var result []struct {
		Start string `db:"start"`
	}
	count, err := query.Load(&result)
	if err != nil {
		log.Fatalln(err)
	}

	log.Printf("count %d  select %v\n", count, result)
}
```

**Comment by DoubleDi** [comment]
ClickHouse has 2 interfaces, the native TCP (port 9000) and the HTTP (port 8123). the `github.com/mailru/go-clickhouse` driver uses the HTTP interface. so you need to specify http://default@host:8123/default. The `github.com/clickhouse/clichouse-go` uses the native TCP interface on 9000, so you have to specify TCP://...:9000

**Comment by sir-farfan** [comment]
Thanks, I thought both implemented the same interfaces in different ways, this makes sense now.
